made changes
AndresM125/AtavusImport pull request #1
Opened 2022-07-13 23:58 UTC by TonyPNguyen

Hey can you let me know if this is good

2022-07-13 23:59 UTC, AndresM125 requested changes

2022-07-13 23:59 UTC, AndresM125 commented on AtavusUserMatcher/ClientApp/src/pages/AdminLogin.js
> +    console.log(username);
why logs in prod?

2022-07-14 00:01 UTC, AndresM125 commented on AtavusUserMatcher/ClientApp/src/App.js
> -  render() {
should be there

2022-07-14 00:01 UTC, AndresM125 commented on AtavusUserMatcher/ClientApp/src/pages/AdminLogin.js
> +const AdminLogin = () => {
hi

2022-07-14 00:01 UTC, AndresM125 commented on AtavusUserMatcher/ClientApp/src/pages/Index.js
> +  }
test

2022-07-14 00:02 UTC, TonyPNguyen commented on AtavusUserMatcher/ClientApp/src/App.js
> -  render() {
lol....

2022-07-14 00:02 UTC, merged